server:
  port: 8083
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID

oauth2-server-url: http://localhost:8081
resources-server-url: http://localhost:8082

spring:
  application:
    name: app-client
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 921a530db40153a6edf0
            client-secret: ad85ccb2960dfecd2eeee81448aba76c219d3564
          my-app:
            client-id: app_client_id
            client-secret: app_client_secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: "read,write"
            client-name: "My APP"
        provider:
          my-app:
            authorization-uri: ${oauth2-server-url}/oauth/authorize
            token-uri: ${oauth2-server-url}/oauth/token
            user-info-uri: ${resources-server-url}/userInfo
            user-name-attribute: userName
